services:
  - type: web
    name: hola-guinea
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT "app:create_app()"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: EMBASSY_VISA_URL
        value: https://www.guineaecuatorialembassy.com/
      - key: DATABASE_URL
        sync: false
      - key: PUBLIC_BASE_URL
        sync: false
